title: Quick Thoughts
description: Some quick thoughts on software development, AI, and startups.
baseurl: ""
url: "https://quickthoughts.ca" # the base hostname & protocol for your site
author:
  email: blog@quickthoughts.ca

collections:
  posts:
    output: true
    permalink: /posts/:title/ # Correctly set to link posts at the root level

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Custom category permalink
defaults:
  - scope:
      path: "" # Applies to all posts
    values:
      layout: "post"
      permalink: "/posts/:title/" # Ensure this matches the new structure
